GET http://localhost:5050

####
GET http://localhost:5050/posts

####

GET http://localhost:5050/posts?page=2&pageSize=3

####
POST http://localhost:5050/posts/create HTTP/1.1
Content-Type: application/json

{
    "category": "Finanza",
    "title": "Post Dodici",
    "readTime": {
        "value": 666,
        "unit": "views"
    },
    "author":{
        "name":"Gabriele Naso"
        },
    "content": "Favoloso!!!!!"
}

####
PATCH http://localhost:5050/posts/update/651706bb28ac97fe58a536a7
Content-Type: application/json

{
    "category": "Spaziale",
    "title": "Post Uno",
    "readTime": {
        "value": 700,
        "unit": "views"
    },
    "content": "Favoloso!!!!!"
}

####
DELETE http://localhost:5050/posts/delete/651706bb28ac97fe58a536a7

####
POST http://localhost:5050/authors/create HTTP/1.1
Content-Type: application/json

{
    "nome":"Gabriele",
    "cognome":"Nasone",
    "dataDiNascita": "1987-04-11",
    "email": "everybody@gmail.com",
    "avatar": "https://media.istockphoto.com/id/1393750072/vector/flat-white-icon-man-for-web-design-silhouette-flat-illustration-vector-illustration-stock.jpg?s=612x612&w=0&k=20&c=s9hO4SpyvrDIfELozPpiB_WtzQV9KhoMUP9R9gVohoU="
}

####

GET http://localhost:5050/authors

####

GET http://localhost:5050/authors/65170bdfe31dc359439b15af/posts

####
PUT http://localhost:5050/authors/update/65170b8fe31dc359439b15ad HTTP/1.1
Content-Type: application/json

{
    "nome":"Frank",
    "cognome":"Sinatra",
    "dataDiNascita": "1700-04-06",
    "email": "everybodysingandsong@gmail.com",
    "avatar": "https://media.istockphoto.com/id/1393750072/vector/flat-white-icon-man-for-web-design-silhouette-flat-illustration-vector-illustration-stock.jpg?s=612x612&w=0&k=20&c=s9hO4SpyvrDIfELozPpiB_WtzQV9KhoMUP9R9gVohoU="
}

####
DELETE  http://localhost:5050/authors/delete/65170b8fe31dc359439b15ad 